'use client';
/* Pre-generated WebP previews are already resized and compressed. */
/* oxlint-disable next/no-img-element */
import {useEffect,useMemo,useState} from 'react';
import Link from '@/components/site-link';
import demos from '@/lib/demos.json';
import {industries} from '@/lib/industries';
import {readFavorites,storeFavorites} from '@/lib/favorites';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Demo=typeof demos[number];
export default function Catalog({initialIndustry='',compact=false}:{initialIndustry?:string,compact?:boolean}){
 const [industry,setIndustry]=useState(initialIndustry);const [style,setStyle]=useState('all');const [query,setQuery]=useState('');const [saved,setSaved]=useState<string[]>([]);const [onlySaved,setOnlySaved]=useState(false);const [limit,setLimit]=useState(12);const [selected,setSelected]=useState<Demo|null>(null);const [live,setLive]=useState(false);const [device,setDevice]=useState('desktop');const [notice,setNotice]=useState('');const [filtersOpen,setFiltersOpen]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{setSaved(readFavorites());const params=new URLSearchParams(location.search);if(!initialIndustry&&industries.some(i=>i.id===params.get('bransje')))setIndustry(params.get('bransje')!);const d=demos.find(d=>d.id===params.get('demo'));if(d){const mobile=window.matchMedia('(max-width: 680px)').matches;setSelected(d);setDevice(mobile?'mobile':'desktop');setLive(mobile)}},0);return()=>clearTimeout(timer)},[initialIndustry]);
 const filtered=useMemo(()=>demos.filter(d=>(!industry||d.industry===industry)&&(style==='all'||d.style===style)&&(!onlySaved||saved.includes(d.id))&&`${d.title} ${d.industryName}`.toLocaleLowerCase('nb').includes(query.toLocaleLowerCase('nb'))),[industry,style,query,onlySaved,saved]);
 function toggle(id:string){setSaved(previous=>{if(!previous.includes(id)&&previous.length>=12){setNotice('Du kan lagre opptil 12 favoritter. Fjern én for å legge til en ny.');return previous}const next=previous.includes(id)?previous.filter(v=>v!==id):[...previous,id];storeFavorites(next);setNotice(next.includes(id)?'Designet er lagt til i favorittene dine.':'Designet er fjernet fra favorittene.');return next})}
 function open(d:Demo){const mobile=window.matchMedia('(max-width: 680px)').matches;setSelected(d);setLive(mobile);setDevice(mobile?'mobile':'desktop');const u=new URL(location.href);u.searchParams.set('demo',d.id);history.replaceState(null,'',u)}
 function close(){setSelected(null);setLive(false);const u=new URL(location.href);u.searchParams.delete('demo');history.replaceState(null,'',u)}
 function changeIndustry(value:string){setIndustry(value);setLimit(12);if(!compact){const u=new URL(location.href);if(value)u.searchParams.set('bransje',value);else u.searchParams.delete('bransje');history.replaceState(null,'',u)}}
 // WebMCP registers once; the action uses the same visible state as the controls.
 // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'filter_sidemannen_designs',description:'Filter the visible Sidemannen design catalog by an industry ID; returns the matching design IDs.',inputSchema:{type:'object',properties:{industry:{type:'string'}},required:['industry'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {industry?:unknown})?.industry;if(typeof id!=='string'||(id!==''&&!industries.some(i=>i.id===id)))throw new Error('Unknown industry');changeIndustry(id);setQuery('');setStyle('all');setOnlySaved(false);return {industry:id,designs:demos.filter(d=>!id||d.industry===id).map(d=>({id:d.id,title:d.title}))}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const current=industries.find(i=>i.id===industry);
 const styleLabel=style==='all'?'Alle uttrykk':style==='Moderne'?'Rent og moderne':'Redaksjonelt / særpreget';
 return <div className={'catalog '+(compact?'compact':'')}><div className="catalog-toolbar">{!compact&&<div className="filter-field industry-filter"><span id="industry-label">Din bransje</span><Select value={industry} onValueChange={v=>changeIndustry(v||'')}><SelectTrigger aria-labelledby="industry-label" className="filter-select"><SelectValue>{current?.name||'Alle bransjer'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="">Alle bransjer</SelectItem>{industries.map(i=><SelectItem key={i.id} value={i.id}>{i.name} ({i.count})</SelectItem>)}</SelectContent></Select></div>}<button type="button" className="catalog-filter-toggle" aria-expanded={filtersOpen} aria-controls="catalog-secondary-filters" onClick={()=>setFiltersOpen(v=>!v)}>{filtersOpen?'Skjul filtre':'Flere filtre'} <span aria-hidden="true">{filtersOpen?'−':'+'}</span></button><div id="catalog-secondary-filters" className={'catalog-secondary-filters '+(filtersOpen?'open':'')}><div className="filter-field"><label htmlFor="design-search">Søk i design</label><input id="design-search" type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12)}} placeholder="Navn eller bransje"/></div><div className="filter-field"><span id="style-label">Uttrykk</span><Select value={style} onValueChange={v=>{setStyle(v||'all');setLimit(12)}}><SelectTrigger className="filter-select" aria-labelledby="style-label"><SelectValue>{styleLabel}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Alle uttrykk</SelectItem><SelectItem value="Moderne">Rent og moderne</SelectItem><SelectItem value="Redaksjonell">Redaksjonelt / særpreget</SelectItem></SelectContent></Select></div></div><button className={'favorite-filter '+(onlySaved?'active':'')} aria-pressed={onlySaved} onClick={()=>{setOnlySaved(!onlySaved);setLimit(12)}}>♡ Mine favoritter <span>{saved.length}</span></button></div>
 {!compact&&<div className="industry-chips" aria-label="Populære bransjer">{['','tannlege','fotograf','renhold','arkitekter','restauranter','hud-og-skjonnhet'].map(id=><button key={id} className={industry===id?'active':''} aria-pressed={industry===id} onClick={()=>changeIndustry(id)}>{industries.find(i=>i.id===id)?.name||'Alle design'}</button>)}</div>}
 <div className="catalog-status"><span aria-live="polite">{filtered.length} design{current?' for '+current.name.toLowerCase():''}</span><span>KONSEPTER, IKKE KUNDEREFERANSER</span></div><output className="sr-only">{notice}</output>
 {filtered.length===0?<div className="empty-state"><h3>{onlySaved?'Ingen favoritter i dette utvalget ennå.':'Ingen design passer med søket.'}</h3><p>Prøv en annen bransje eller nullstill filtrene.</p><button className="button" onClick={()=>{setQuery('');setStyle('all');setOnlySaved(false);changeIndustry(initialIndustry)}}>Nullstill filtre ↗</button></div>:<div className="catalog-grid">{filtered.slice(0,limit).map((d,i)=><article className="design-entry" key={d.id}><button className="design-picture" onClick={()=>open(d)} aria-label={`Forhåndsvis ${d.title}, ${d.id}`}><div className="browser-bar"><span>● ● ●</span><span>{d.industryName}</span><span>↗</span></div><img src={d.image} alt={`Designkonsept: ${d.title}`} width="1200" height="850" loading={i<2?'eager':'lazy'}/><span className="preview-hint">Se nærmere ↗</span></button><div className="design-info"><div><span className="design-meta">{d.industryName} / {d.style}</span><h3><button onClick={()=>open(d)}>{d.title}</button></h3></div><button className={'save-button '+(saved.includes(d.id)?'saved':'')} onClick={()=>toggle(d.id)} aria-pressed={saved.includes(d.id)} aria-label={`${saved.includes(d.id)?'Fjern':'Lagre'} ${d.title} som favoritt`}>{saved.includes(d.id)?'♥':'♡'}</button></div></article>)}</div>}
 {filtered.length>limit&&<div className="load-more"><button className="button" onClick={()=>setLimit(limit+12)}>Vis flere design <span>↓</span></button><span>{Math.min(limit,filtered.length)} av {filtered.length}</span></div>}
 {saved.length>0&&<aside className="favorites-tray" aria-label="Valgte favoritter"><span><strong>{saved.length}</strong> {saved.length===1?'uttrykk du liker':'uttrykk du liker'}</span><Link href={`/kontakt?design=${saved.join(',')}`} className="button acid small">Ta neste steg →</Link></aside>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)close()}}><DialogContent className="demo-dialog" showCloseButton={false}>{selected&&<><div className="preview-header"><div><DialogTitle className="preview-title">{selected.title}</DialogTitle><DialogDescription>{selected.industryName} · Designkonsept</DialogDescription></div><DialogClose className="close-button" aria-label="Lukk forhåndsvisning">✕</DialogClose></div><Tabs value={device} onValueChange={v=>setDevice(String(v))}><TabsList className="device-tabs" aria-label="Velg skjermstørrelse"><TabsTrigger value="desktop">Desktop</TabsTrigger><TabsTrigger value="mobile" onClick={()=>setLive(true)}>Mobil</TabsTrigger></TabsList><TabsContent value="desktop"><div className="demo-stage">{live?<iframe src={selected.url} title={`${selected.title} på desktop`} sandbox="allow-scripts" referrerPolicy="no-referrer"/>:<img className="large-preview" src={selected.image} alt={`Forhåndsvisning av ${selected.title}`} width="1200" height="850"/>}</div></TabsContent><TabsContent value="mobile"><div className="demo-stage mobile"><iframe src={selected.url} title={`${selected.title} på mobil`} sandbox="allow-scripts" referrerPolicy="no-referrer"/></div></TabsContent></Tabs><div className="preview-actions"><button className="button small" onClick={()=>toggle(selected.id)}>{saved.includes(selected.id)?'♥ Lagret':'♡ Lagre favoritt'}</button>{!live&&device==='desktop'&&<button className="text-link" onClick={()=>setLive(true)}>Prøv demoen</button>}<a className="text-link" href={selected.url} target="_blank" rel="noopener noreferrer">Åpne hele ↗</a><Link className="button dark small preview-primary" href={`/kontakt?design=${selected.id}`}>Jeg liker denne →</Link></div><p className="demo-note">Innhold, navn og priser i demoen er illustrasjoner. Din nettside tilpasses bedriften din.</p></>}</DialogContent></Dialog>
 </div>
}
