'use client';
/* Small, pre-generated WebP selections avoid loading the full demo. */
/* oxlint-disable next/no-img-element */
import {useEffect,useState} from 'react';import Link from '@/components/site-link';import demos from '@/lib/demos.json';import {readFavorites} from '@/lib/favorites';
export default function ContactForm(){const [selected,setSelected]=useState<string[]>([]);const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const [error,setError]=useState('');const [reference,setReference]=useState('');const [started,setStarted]=useState(0);const [requestId,setRequestId]=useState('');
useEffect(()=>{const timer=setTimeout(()=>{const ids=new URLSearchParams(location.search).get('design')?.split(',')||readFavorites();setSelected([...new Set(ids)].filter(id=>demos.some(d=>d.id===id)).slice(0,12));setStarted(Date.now());setRequestId(crypto.randomUUID())},0);return()=>clearTimeout(timer)},[]);
async function submit(e:{preventDefault():void;currentTarget:HTMLFormElement}){e.preventDefault();setStatus('sending');const data=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch('/api/inquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,designs:selected,started,requestId})});const payload=await response.json() as {error?:string;reference:string};if(!response.ok)throw new Error(payload.error||'Kunne ikke sende forespørselen. Prøv igjen.');setReference(payload.reference);setStatus('success')}catch(err){setError(err instanceof Error?err.message:'Noe gikk galt. Prøv igjen.');setStatus('error')}}
if(status==='success')return <div className="form-success" aria-live="polite"><span className="success-mark">✓</span><h2>Takk. Da er vi i gang.</h2><p>Forespørselen din er mottatt. Vi følger opp på e-postadressen du oppga.</p><p className="form-note">Din referanse: {reference}</p><Link href="/portfolio" className="button dark">Se flere design ↗</Link></div>;
return <form onSubmit={submit} className="contact-form">{selected.length>0&&<fieldset className="selected-designs"><legend>Dine designfavoritter</legend>{selected.map(id=>{const d=demos.find(d=>d.id===id)!;return <div key={id}><img src={d.image} alt="" width="90" height="64"/><span>{d.title}<small>{d.industryName}</small></span><button type="button" onClick={()=>setSelected(selected.filter(v=>v!==id))} aria-label={`Fjern ${d.title}`}>×</button></div>})}</fieldset>}<div className="form-row"><label>Navnet ditt<input name="name" autoComplete="name" required maxLength={100} placeholder="Fornavn og etternavn"/></label><label>E-post<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="deg@bedriften.no"/></label></div><div className="form-row"><label>Bedrift <span>(valgfritt)</span><input name="company" autoComplete="organization" maxLength={150} placeholder="Bedriftens navn"/></label><label>Telefon <span>(valgfritt)</span><input name="phone" type="tel" autoComplete="tel" maxLength={30} placeholder="Telefonnummer"/></label></div><label>Hva ser du for deg?<textarea name="message" required minLength={10} maxLength={5000} rows={5} placeholder="Fortell litt om bedriften og hva du trenger. Det er helt greit å ikke ha alle svarene."/></label><div className="honeypot" aria-hidden="true"><label>La dette feltet stå tomt<input name="website" autoComplete="off" tabIndex={-1}/></label></div><p className="form-note">Vi bruker opplysningene til å svare på forespørselen din. Ikke skriv sensitive opplysninger. <Link href="/personvern">Les om personvern.</Link></p>{status==='error'&&<p className="form-error" role="alert">{error}</p>}<button className="button dark" type="submit" disabled={status==='sending'}>{status==='sending'?'Sender …':'Send forespørsel'} <span>↗</span></button><p className="form-note">En forespørsel er ikke en bestilling.</p></form>}
