import Link from '@/components/site-link';import {notFound} from 'next/navigation';import Catalog from '@/components/catalog';import {industries} from '@/lib/industries';import {seo,site} from '@/lib/site';
const relatedGroups=[
 ['byggmestere','entreprenorer','elektrikere','rorlegger','murere','blikkenslagere','anleggsgartnere','varmepumpe','lassmeder','trefelling','eiendomsservice'],
 ['renhold','flyttebyraer','skadedyrfirma','eiendomsservice','lassmeder'],
 ['velvaereklinikker','hud-og-skjonnhet','frisorer','tannlege','dyreklinikker'],
 ['bilforhandlere','bilpleie','bilverksteder','trafikkskoler'],
 ['restauranter','catering','overnattingssteder'],
 ['advokater','regnskapsforere','arkitekter','fotograf']
];
const searchNames:Record<string,string>={velvaereklinikk:'velværeklinikk',tannlege:'tannlege',fotograf:'fotograf',renhold:'renholdsfirma',advokat:'advokat',anleggsgartner:'anleggsgartner',arkitekt:'arkitekt',bilforhandler:'bilforhandler',bilpleie:'bilpleie',bilverksted:'bilverksted',blikkenslager:'blikkenslager',byggmester:'byggmester',catering:'cateringfirma',dyreklinikk:'dyreklinikk',elektriker:'elektriker',entreprenor:'entreprenør',flyttebyra:'flyttebyrå',frisor:'frisør',hudpleie:'hudpleieklinikk',varmepumpe:'varmepumpefirma',lassmed:'låssmed',murer:'murer',overnattingssted:'overnattingssted',regnskapsforer:'regnskapsfører',restaurant:'restaurant',rorlegger:'rørlegger',skadedyrkontroll:'skadedyrfirma',trafikkskole:'trafikkskole',trefelling:'trefelling',eiendomsservice:'eiendomsservice'};
function getRelated(id:string){const preferred=[...new Set(relatedGroups.filter(group=>group.includes(id)).flat())].filter(candidate=>candidate!==id);return preferred.map(candidate=>industries.find(i=>i.id===candidate)).filter((i):i is typeof industries[number]=>Boolean(i)).slice(0,5)}
export function generateStaticParams(){return industries.map(i=>({industry:`nettside-${i.slug}`}))}
export const dynamicParams=false;
type Props={params:Promise<{industry:string}>};
export async function generateMetadata({params}:Props){const {industry}=await params;const i=industries.find(i=>industry===`nettside-${i.slug}`);return i?seo(`Nettside for ${searchNames[i.slug]||i.name.toLowerCase()} – fra 2 000 kr`,`${i.headline} Se ${i.count} designretninger og få en nettside tilpasset virksomheten din fra 2 000 kr.`,`/${industry}/`):{title:'Siden finnes ikke'}}
export default async function IndustryPage({params}:Props){const {industry}=await params;const i=industries.find(i=>industry===`nettside-${i.slug}`);if(!i)notFound();const related=getRelated(i.id);return <main id="main"><section className="wrap industry-heading"><div className="breadcrumbs"><Link href="/bransjer">Bransjer</Link><span>/</span><span>{i.name}</span></div><div className="eyebrow">NETTSIDE FOR {i.name.toLocaleUpperCase('nb')} · FRA 2 000 KR</div><h1>{i.headline}</h1><div className="industry-intro"><p>{i.intro}</p><a className="button dark" href="#design">Se {i.count} design <span>↓</span></a></div></section><section className="industry-needs wrap"><div><span className="eyebrow">FRA BESØK TIL HENVENDELSE</span><h2>Bygget rundt det<br/>kunden trenger.</h2></div><ol>{i.features.map((f,n)=><li key={f}><span>0{n+1}</span>{f}</li>)}</ol></section><section className="wrap industry-designs" id="design"><div className="section-heading"><h2>Finn din retning.</h2><span>{i.count} ulike muligheter</span></div><Catalog initialIndustry={i.id} compact/></section><section className="wrap industry-answer"><span className="eyebrow">ET SPØRSMÅL FRA DIN BRANSJE</span><h2>{i.question}</h2><p>{i.answer}</p><Link href="/kontakt" className="button dark">Få fast pris →</Link></section><section className="wrap related"><h2>Se flere bransjer</h2><div>{related.map(r=><Link key={r.id} href={`/nettside-${r.slug}`}>{r.name} →</Link>)}<Link href="/bransjer">Alle bransjer →</Link></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Bransjer',item:site.origin+'/bransjer'},{'@type':'ListItem',position:2,name:i.name,item:site.origin+'/'+industry}]})}}/></main>}
